"""initial schema

Revision ID: 4a1979c0a962
Revises:
Create Date: 2026-09-16 18:46:05.312329
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a1979c0a962"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("store_name", sa.String(length=150), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("external_store_id", sa.String(length=128), nullable=True),
        sa.Column("owner_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_stores_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stores_platform_status", "stores", ["platform", "status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin','operator','viewer')", name="ck_users_role"),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_users_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("detail_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_logs_target", "audit_logs", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("import_type", sa.String(length=40), nullable=False),
        sa.Column("batch_status", sa.String(length=20), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("success_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "batch_status IN ('uploaded','validated','importing','completed','failed','cancelled')",
            name="ck_import_batches_status",
        ),
        sa.CheckConstraint(
            "import_type IN ('products','sku_inventory','performance_records','platform_mappings')",
            name="ck_import_batches_type",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_import_batches_type_status",
        "import_batches",
        ["import_type", "batch_status"],
        unique=False,
    )
    op.create_table(
        "platform_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("account_name", sa.String(length=128), nullable=False),
        sa.Column("auth_status", sa.String(length=20), nullable=False),
        sa.Column("auth_meta_json", sa.JSON(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auth_status IN ('unconfigured','pending','authorized','expired','revoked','failed')",
            name="ck_platform_accounts_auth_status",
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "platform", "account_name", name="uq_platform_account"),
    )
    op.create_index(
        op.f("ix_platform_accounts_store_id"), "platform_accounts", ["store_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("selling_points", sa.Text(), nullable=True),
        sa.Column("product_url", sa.String(length=2048), nullable=True),
        sa.Column("images_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft','active','inactive')", name="ck_products_status"),
        sa.CheckConstraint("cost IS NULL OR cost >= 0", name="ck_products_cost"),
        sa.CheckConstraint("price >= 0", name="ck_products_price"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_products_platform_category", "products", ["platform", "category"], unique=False
    )
    op.create_index("ix_products_store_status", "products", ["store_id", "status"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("setting_key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_sensitive", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_type IN ('string','integer','decimal','boolean','json')",
            name="ck_system_settings_value_type",
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("setting_key"),
    )
    op.create_table(
        "ad_recommendations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("objective_text", sa.Text(), nullable=True),
        sa.Column("audience_segments_json", sa.JSON(), nullable=True),
        sa.Column("budget_plan_json", sa.JSON(), nullable=True),
        sa.Column("creative_tests_json", sa.JSON(), nullable=True),
        sa.Column("bid_strategy_json", sa.JSON(), nullable=True),
        sa.Column("risk_controls_json", sa.JSON(), nullable=True),
        sa.Column("next_steps_json", sa.JSON(), nullable=True),
        sa.Column("confirm_status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_by", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirm_remark", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confirm_status IN ('pending','confirmed','rejected')",
            name="ck_ad_recommendations_confirm_status",
        ),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ad_recommendations_product_created",
        "ad_recommendations",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "competitors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sales_hint", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("main_image", sa.String(length=2048), nullable=True),
        sa.Column("selling_points", sa.Text(), nullable=True),
        sa.Column("review_keywords", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price IS NULL OR price >= 0", name="ck_competitors_price"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_competitors_product_platform", "competitors", ["product_id", "platform"], unique=False
    )
    op.create_table(
        "creative_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("plan_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("rationale_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan_type IN ('main_image','video_script','title')", name="ck_creative_plans_type"
        ),
        sa.CheckConstraint(
            "status IN ('draft','selected','archived')", name="ck_creative_plans_status"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_creative_plans_product_type_status",
        "creative_plans",
        ["product_id", "plan_type", "status"],
        unique=False,
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("row_status", sa.String(length=20), nullable=False),
        sa.Column("raw_data_json", sa.JSON(), nullable=True),
        sa.Column("normalized_data_json", sa.JSON(), nullable=True),
        sa.Column("errors_json", sa.JSON(), nullable=True),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "row_status IN ('valid','invalid','imported','failed')", name="ck_import_rows_status"
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_import_row_number"),
    )
    op.create_index(
        "ix_import_rows_batch_status", "import_rows", ["batch_id", "row_status"], unique=False
    )
    op.create_table(
        "platform_product_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_product_id", sa.String(length=128), nullable=False),
        sa.Column("platform_sku_id", sa.String(length=128), nullable=False),
        sa.Column("mapping_status", sa.String(length=20), nullable=False),
        sa.Column("raw_payload_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mapping_status IN ('active','inactive','invalid')",
            name="ck_platform_product_mappings_status",
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "platform",
            "platform_product_id",
            "platform_sku_id",
            name="uq_platform_product_mapping",
        ),
    )
    op.create_index(
        op.f("ix_platform_product_mappings_product_id"),
        "platform_product_mappings",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_skus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku_code", sa.String(length=100), nullable=False),
        sa.Column("sku_name", sa.String(length=255), nullable=False),
        sa.Column("spec_json", sa.JSON(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("platform_sku_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_product_skus_status"),
        sa.CheckConstraint("cost IS NULL OR cost >= 0", name="ck_product_skus_cost"),
        sa.CheckConstraint("price >= 0", name="ck_product_skus_price"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "sku_code", name="uq_product_sku_code"),
    )
    op.create_index(
        op.f("ix_product_skus_product_id"), "product_skus", ["product_id"], unique=False
    )
    op.create_table(
        "promotion_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("link_name", sa.String(length=255), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("tracking_code", sa.String(length=64), nullable=False),
        sa.Column("utm_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("click_count", sa.BigInteger(), nullable=False),
        sa.Column("scene_text", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_promotion_links_status"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_code"),
    )
    op.create_index(
        "ix_promotion_links_product_status",
        "promotion_links",
        ["product_id", "status"],
        unique=False,
    )
    op.create_table(
        "public_link_parse_tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("task_status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "task_status IN ('pending','running','succeeded','failed','cancelled','timeout')",
            name="ck_public_link_parse_tasks_status",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_public_link_parse_tasks_attempts"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_link_parse_tasks_product_status",
        "public_link_parse_tasks",
        ["product_id", "task_status"],
        unique=False,
    )
    op.create_table(
        "review_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("insights_json", sa.JSON(), nullable=True),
        sa.Column("problem_analysis_json", sa.JSON(), nullable=True),
        sa.Column("next_actions_json", sa.JSON(), nullable=True),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_review_reports_period"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_reports_product_period",
        "review_reports",
        ["product_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_table(
        "competitor_monitors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("monitor_status", sa.String(length=20), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "monitor_status IN ('active','paused','failed')", name="ck_competitor_monitors_status"
        ),
        sa.CheckConstraint("interval_minutes >= 10", name="ck_competitor_monitors_interval"),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competitor_id", name="uq_competitor_monitor"),
    )
    op.create_index(
        "ix_competitor_monitors_due",
        "competitor_monitors",
        ["monitor_status", "next_run_at"],
        unique=False,
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("creative_plan_id", sa.Integer(), nullable=False),
        sa.Column("job_kind", sa.String(length=20), nullable=False),
        sa.Column("job_status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("provider_name", sa.String(length=50), nullable=True),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("job_kind IN ('image','video')", name="ck_generation_jobs_kind"),
        sa.CheckConstraint(
            "job_status IN ('pending','running','succeeded','failed','cancelled','timeout')",
            name="ck_generation_jobs_status",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_generation_jobs_attempts"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_generation_jobs_max_attempts"),
        sa.ForeignKeyConstraint(["cancelled_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["creative_plan_id"], ["creative_plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_generation_jobs_idempotency"),
    )
    op.create_index(
        "ix_generation_jobs_claim",
        "generation_jobs",
        ["job_status", "next_run_at", "locked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_jobs_external_job_id"),
        "generation_jobs",
        ["external_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_generation_jobs_product_created",
        "generation_jobs",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=False),
        sa.Column("locked_qty", sa.Integer(), nullable=False),
        sa.Column("warning_threshold", sa.Integer(), nullable=False),
        sa.Column("location_text", sa.String(length=255), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("locked_qty >= 0", name="ck_inventory_items_locked"),
        sa.CheckConstraint("stock_qty >= 0", name="ck_inventory_items_stock"),
        sa.CheckConstraint("warning_threshold >= 0", name="ck_inventory_items_warning"),
        sa.ForeignKeyConstraint(["sku_id"], ["product_skus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku_id"),
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=40), nullable=False),
        sa.Column("change_qty", sa.Integer(), nullable=False),
        sa.Column("before_qty", sa.Integer(), nullable=False),
        sa.Column("after_qty", sa.Integer(), nullable=False),
        sa.Column("reason_text", sa.String(length=500), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("after_qty >= 0", name="ck_inventory_movements_after"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sku_id"], ["product_skus.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_movements_sku_created",
        "inventory_movements",
        ["sku_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "product_diagnoses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_review_report_id", sa.Integer(), nullable=True),
        sa.Column("positioning", sa.Text(), nullable=True),
        sa.Column("price_band", sa.Text(), nullable=True),
        sa.Column("audience_insights", sa.Text(), nullable=True),
        sa.Column("pain_points", sa.Text(), nullable=True),
        sa.Column("selling_point_analysis", sa.Text(), nullable=True),
        sa.Column("risks", sa.Text(), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_review_report_id"], ["review_reports.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_product_diagnoses_product_created",
        "product_diagnoses",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "promotion_link_clicks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("promotion_link_id", sa.Integer(), nullable=False),
        sa.Column(
            "clicked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("client_ip_hash", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["promotion_link_id"], ["promotion_links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_promotion_link_clicks_link_clicked",
        "promotion_link_clicks",
        ["promotion_link_id", "clicked_at"],
        unique=False,
    )
    op.create_table(
        "competitor_monitor_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sales_hint", sa.String(length=255), nullable=True),
        sa.Column("selling_points", sa.Text(), nullable=True),
        sa.Column("raw_payload_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["competitor_monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_monitor_snapshots_monitor_created",
        "competitor_monitor_snapshots",
        ["monitor_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "generated_assets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("creative_plan_id", sa.Integer(), nullable=False),
        sa.Column("generation_job_id", sa.BigInteger(), nullable=True),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("asset_url", sa.String(length=2048), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_sec", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("usage_scene", sa.String(length=255), nullable=True),
        sa.Column("score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("tags_json", sa.JSON(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("asset_type IN ('image','video')", name="ck_generated_assets_type"),
        sa.CheckConstraint(
            "review_status IN ('pending','approved','rejected')",
            name="ck_generated_assets_review_status",
        ),
        sa.CheckConstraint("score IS NULL OR (score >= 0 AND score <= 5)", name="ck_assets_score"),
        sa.ForeignKeyConstraint(["creative_plan_id"], ["creative_plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["generation_job_id"], ["generation_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "creative_plan_id", "asset_type", "version_no", name="uq_asset_plan_version"
        ),
    )
    op.create_index(
        "ix_generated_assets_product_review",
        "generated_assets",
        ["product_id", "review_status"],
        unique=False,
    )
    op.create_table(
        "generation_job_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_message", sa.Text(), nullable=True),
        sa.Column("event_data_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_events_job_created", "generation_job_events", ["job_id", "created_at"], unique=False
    )
    op.create_table(
        "ad_experiments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=True),
        sa.Column("related_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("related_link_id", sa.Integer(), nullable=True),
        sa.Column("experiment_name", sa.String(length=255), nullable=False),
        sa.Column("target_text", sa.Text(), nullable=True),
        sa.Column("audience_text", sa.Text(), nullable=True),
        sa.Column("budget_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("success_metric_text", sa.Text(), nullable=True),
        sa.Column("hypothesis_text", sa.Text(), nullable=True),
        sa.Column("experiment_status", sa.String(length=20), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experiment_status IN ('draft','confirmed','running','finished','cancelled')",
            name="ck_ad_experiments_status",
        ),
        sa.CheckConstraint("budget_amount >= 0", name="ck_ad_experiments_budget"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["ad_recommendations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["related_asset_id"], ["generated_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_link_id"], ["promotion_links.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ad_experiments_product_status",
        "ad_experiments",
        ["product_id", "experiment_status"],
        unique=False,
    )
    op.create_table(
        "performance_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("creative_plan_id", sa.Integer(), nullable=True),
        sa.Column("generated_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("promotion_link_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("ctr", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("conversions", sa.BigInteger(), nullable=False),
        sa.Column("conversion_rate", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("clicks >= 0", name="ck_performance_records_clicks"),
        sa.CheckConstraint("conversions >= 0", name="ck_performance_records_conversions"),
        sa.CheckConstraint("impressions >= 0", name="ck_performance_records_impressions"),
        sa.CheckConstraint("period_end >= period_start", name="ck_performance_records_period"),
        sa.CheckConstraint("revenue >= 0", name="ck_performance_records_revenue"),
        sa.CheckConstraint("spend >= 0", name="ck_performance_records_spend"),
        sa.ForeignKeyConstraint(["creative_plan_id"], ["creative_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["experiment_id"], ["ad_experiments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["generated_asset_id"], ["generated_assets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["promotion_link_id"], ["promotion_links.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_performance_records_product_period",
        "performance_records",
        ["product_id", "period_start", "period_end"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_performance_records_product_period", table_name="performance_records")
    op.drop_table("performance_records")
    op.drop_index("ix_ad_experiments_product_status", table_name="ad_experiments")
    op.drop_table("ad_experiments")
    op.drop_index("ix_job_events_job_created", table_name="generation_job_events")
    op.drop_table("generation_job_events")
    op.drop_index("ix_generated_assets_product_review", table_name="generated_assets")
    op.drop_table("generated_assets")
    op.drop_index("ix_monitor_snapshots_monitor_created", table_name="competitor_monitor_snapshots")
    op.drop_table("competitor_monitor_snapshots")
    op.drop_index("ix_promotion_link_clicks_link_clicked", table_name="promotion_link_clicks")
    op.drop_table("promotion_link_clicks")
    op.drop_index("ix_product_diagnoses_product_created", table_name="product_diagnoses")
    op.drop_table("product_diagnoses")
    op.drop_index("ix_inventory_movements_sku_created", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_table("inventory_items")
    op.drop_index("ix_generation_jobs_product_created", table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_external_job_id"), table_name="generation_jobs")
    op.drop_index("ix_generation_jobs_claim", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index("ix_competitor_monitors_due", table_name="competitor_monitors")
    op.drop_table("competitor_monitors")
    op.drop_index("ix_review_reports_product_period", table_name="review_reports")
    op.drop_table("review_reports")
    op.drop_index("ix_link_parse_tasks_product_status", table_name="public_link_parse_tasks")
    op.drop_table("public_link_parse_tasks")
    op.drop_index("ix_promotion_links_product_status", table_name="promotion_links")
    op.drop_table("promotion_links")
    op.drop_index(op.f("ix_product_skus_product_id"), table_name="product_skus")
    op.drop_table("product_skus")
    op.drop_index(
        op.f("ix_platform_product_mappings_product_id"), table_name="platform_product_mappings"
    )
    op.drop_table("platform_product_mappings")
    op.drop_index("ix_import_rows_batch_status", table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index("ix_creative_plans_product_type_status", table_name="creative_plans")
    op.drop_table("creative_plans")
    op.drop_index("ix_competitors_product_platform", table_name="competitors")
    op.drop_table("competitors")
    op.drop_index("ix_ad_recommendations_product_created", table_name="ad_recommendations")
    op.drop_table("ad_recommendations")
    op.drop_table("system_settings")
    op.drop_index("ix_products_store_status", table_name="products")
    op.drop_index("ix_products_platform_category", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_platform_accounts_store_id"), table_name="platform_accounts")
    op.drop_table("platform_accounts")
    op.drop_index("ix_import_batches_type_status", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_audit_logs_target", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index("ix_stores_platform_status", table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
