"""add auth token revocations

Revision ID: 7ebf4f3fc50e
Revises: 4a1979c0a962
Create Date: 2026-09-16 19:09:27.323203
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7ebf4f3fc50e"
down_revision: str | Sequence[str] | None = "4a1979c0a962"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_token_revocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_index(
        "ix_auth_token_revocations_expires", "auth_token_revocations", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_token_revocations_user_id"),
        "auth_token_revocations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_token_revocations_user_id"), table_name="auth_token_revocations")
    op.drop_index("ix_auth_token_revocations_expires", table_name="auth_token_revocations")
    op.drop_table("auth_token_revocations")
    # ### end Alembic commands ###
